
services:
  - postgresql

#env:
 # global:
  #  - CODECOV_TOKEN=THIS_VAR_IS_SET_ON_TRAVIS_GUI
  
jobs:
  include:
    
    - language: ruby
      name: "API (Ruby)" 
      rvm:
        - 2.5.7
      cache: bundler
      before_install:
        - cd api
        - gem install bundler:2.1.4 rspec:3.10.0
      install:
        - bundle install
      before_script:
        - rake db:create
        - rake db:migrate
      script:
        - bundle exec rails test
      before_deploy:
        - cd ..
      deploy:
        - provider: script
          script: bash init_heroku_deploy.sh api_hom
          on:
            branch: develop
        
        - provider: script
          script: bash init_heroku_deploy.sh api_prod
          on:
            branch: master

    - language: node.js
      name: "Client (Node.JS)"
      node_js: 14
      cache: yarn
      before_install:
        - cd client
      install:
        - yarn install
        - yarn add codecov@3.8.1
      script:
        - yarn test:unit
        - yarn lint --no-fix
      after_success:
        - codecov
      before_deploy:
        - cd ..
      deploy:
        - provider: script
          script: bash init_heroku_deploy.sh client_hom
          on:
            branch: develop
        
        - provider: script
          script: bash init_heroku_deploy.sh client_prod
          on:
            branch: master