version: '3.5'

volumes:
  db_data:


services:
  db:
    image: postgres:13.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      # development configuration
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    ports:
      - 5432:5432

  api:
    build: ./api
    depends_on:
      - db
    environment:
      - API_DATABASE_HOST=db
    ports:
      - 3000:3000
    command: "rails server -b 0.0.0.0"

  client:
    build: ./client
    ports:
      - 8080:8080
    
